main/urls.py
from django.conf.urls import url, patterns

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^results/$', views.find, name='find'),
]

skatelocal/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main'))
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from lxml import html
import requests
import json
import argparse
import json
import pprint
import sys
import urllib
import urllib2
#import re
import oauth2


GOOGKEY = '&key=AIzaSyBmu-0gJXE0CMNQRYnXeLCM_oN2_WXSR7E'
SEARCHURL = 'https://maps.googleapis.com/maps/api/place/textsearch/json?query='
KEYWORDS = 'skate+shop+'
#MATCH = re.compile("(BOARD)|((SKATE)(.))")
# Create your views here.
def index(request):
	return render(request, 'main/index.html')
def find(request):
	zcode = request.POST['location']
	search = SEARCHURL + KEYWORDS + zcode + GOOGKEY
	page =  urllib.urlopen(search)
	jsonRaw = page.read()
	data = json.loads(jsonRaw)

	shoplist = []
	infolist = []

	biglist = data['results']
	for shops in biglist:
		infolist = []
		infolist.append(shops['name'])
		infolist.append(shops['formatted_address'])
		#shops['formatted_address']
		shoplist.append(infolist)
	return render(request, 'main/results.html', {'shoplist' : shoplist})

main/templates/main/index.html
{% load staticfiles %}
<html>
<head>
	<title>Skate Local</title>
	<link rel="stylesheet" type="text/css" href="{% static "css/mainstyle.css" %}">
	<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</head>

<body>
	<div id = "top">
		<div id = "layer">
			<div id = "user">
				<h1>Skate Local</h1>
				<p>find local skate shops/products around you!</P>
				<form action = "{% url 'main:find' %}" method = "post" id = 'form'>
					{% csrf_token %}
				<div id = "location">
					<input type = "text" rows = "1" cols = "14" id = "enter" placeholder = "enter location" name = "location">
				</div>
				<div id = "btn">
					<input type = 'submit' value = "find shops" id = "press">
				</div>
				</form>
			</div>
		</div>	
	</div>
	{% block results %}
	{% endblock %}
	<script>
		/*$(document).ready(function() {
			$('#reveal').hide();
			$('#btn').click(function() {
				if($("textarea").val().length) {
							var code = $('textarea').val()
							$('#reveal').show();
							$('#sorry').html("<p>there's no backend sorry i can't tell you the local skate shops around </p>" + code);					
							//$('#reveal').scrollTop($('#reveal')[0].scrollHeight, 'slow');
							$('body').animate({
									scrollTop: $('#reveal')[0].scrollHeight
							}, 500);
				}
			});
			$('textarea').keypress(function(e) {
				if(e.which == 13) {
					if($("textarea").val().length) {
								var code = $('textarea').val()
								$('#reveal').show();
								$('#sorry').html("<p>there's no backend sorry i can't tell you the local skate shops around </p>" + code);					
								//$('#reveal').scrollTop($('#reveal')[0].scrollHeight, 'slow');
								$('body').animate({
										scrollTop: $('#reveal')[0].scrollHeight
								}, 500);
								e.preventDefault();
								$('textarea').val() = 0;
					}
				}
			});
		});*/
	</script>
</body>
</ntml>

main/templates/main/results.html
{% extends "main/index.html" %}
{% block results %}
{% if shoplist %}
<div id = "shops">
{% for shop in shoplist %}

	{% if shop.0 != 'Zumiez' %}
		<div id = "wrap">
			<div id = "shop">
				<a href = "https://www.google.com/maps/dir/My+Location/{{ shop.1 }}" target = "_blank">
					<div id = "name">
						<h3>{{ shop.0 }}</h3>
					</div>

					<div id = "address">
						{{ shop.1 }}
					</div>
				</a>
			</div>	
		</div>	
	{% endif %}
{% endfor %}

{% else %}
<div id = "noshops">
	No Shops Found.
</div>
{% endif %}
</div>
{% endblock %}